---
- include: install.yml
- include: server.yml
  when: not redis_sentinel
  tags:
    - config
- include: sentinel.yml
  when: redis_sentinel
  tags:
    - config
- include: local_facts.yml

- name: Set fact redis_has_run
  set_fact:
    redis_has_run: true