---

- name: Check if Docker is running
  command: service docker status
  ignore_errors: yes
  changed_when: false
  register: service_docker_status

- name: Report status of Docker
  fail:
    msg: |
      Service Docker is not running.
      Output of `service docker status`:
      {{ service_docker_status.stdout }}
      {{ service_docker_status.stderr }}
  when: service_docker_status | failed

- name: Start Portainer Container
  command: docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 9000:9000 portainer/portainer
