---
- name: create logstash install directory
  file:
    path={{ logstash_install_dir }}/
    state=directory
    mode=0744
  tags: logstash

- name: create logstash conf directory
  file:
    path={{ logstash_conf_dir }}/
    state=directory
    mode=0744
  tags: logstash

- name: check for existing logstash install
  stat: path={{ logstash_install_dir }}/logstash-{{ logstash_version }}
  register: logstash
  tags: logstash

- name: download logstash
  get_url:
    url={{ repository_infrastructure }}/logstash-{{ logstash_version }}.tar.gz
    dest=/tmp/logstash-{{ logstash_version }}.tar.gz
    mode=0644
    validate_certs=no
  when: logstash.stat.isdir is not defined
  tags: logstash

- name: extract logstash
  unarchive:
    src=/tmp/logstash-{{ logstash_version }}.tar.gz
    dest={{ logstash_install_dir }}/
    copy=no
  when: logstash.stat.isdir is not defined
  tags: logstash

- name: delete temporary logstash file
  file:
    path=/tmp/logstash-{{ logstash_version }}.tar.gz
    state=absent
  ignore_errors: yes
  tags: logstash

- name: create logstash symlink
  file:
    path={{ logstash_install_dir }}/default
    state=link
    src={{ logstash_install_dir }}/logstash-{{ logstash_version }}
  tags: logstash

- name: create logstash template directory
  file:
    path={{ logstash_template_dir }}
    state=directory
  tags: logstash

- name: copy supervisord config
  template:
    src=logstash-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/logstash-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: logstash

- name: add logstash to supervisord
  supervisorctl:
    name: logstash
    state: present
  tags:
    - logstash

- name: ensure logstash is started
  supervisorctl:
    name: logstash
    state: started
  tags:
    - logstash

- name: Set fact logstash_has_run
  set_fact:
    logstash_has_run: true
