# Streamparse does not support using conda, it requires virtualenv.
# Have to compile python from source and manually create a virtualenv.
# Note that installing both miniconda and virtualenv tends to break things.
# Guide used to provision is here:
# https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'