---
# docker-engine is the default package name
docker_pkg_name: docker-engine
docker_apt_cache_valid_time: 600

docker_user: docker
docker_group: docker
docker_start_secs: 10
docker_start_retries: 3

# docker dns path for docker.io package ( changed at ubuntu 14.04 from docker to docker.io )
docker_defaults_file_path: /etc/default/docker

# Place to get apt repository key
docker_apt_key_url: https://apt.dockerproject.org/gpg
docker_apt_key_sig: 2C52609D
docker_apt_repository: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main

# Versions for the python packages that are installed installed
docker_py_version: latest
docker_compose_version: latest

# Set to 'yes' or 'true' to enable updates (sets 'latest' in apt module)
docker_update_package: yes

# Change these to 'present' if you're running Ubuntu 12.04-13.10 and are fine with less-than-latest packages
docker_kernel_pkg_state: latest

docker_pidproxy_install_dir: /opt/pidproxy
docker_pid_file: "{{ docker_pidproxy_install_dir }}/docker.pid"
docker_stop_signal: INT

docker_install_ctop: true

################################
# Docker daemon configuration
################################
docker_config_dir: /etc/docker
docker_daemon_config_path: "{{ docker_config_dir }}/daemon.json"

###########################################################################################
# See all options here:
# https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
###########################################################################################
docker_daemon_conf:
  log-driver: 'json-file'
  log-opts:
    max-size: '50m'
    max-file: '3'
