---

- name: make sure volumes have filesystems
  filesystem:
    fstype: ext4
    dev: "{{ item }}"
  when: dfs_internap
  with_items:
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    - /dev/sdf
    - /dev/sdg
  tags:
    - hadoop
    - hdfs_datanode

- name: mount directories to volumes
  mount:
    name={{ item.dir }}
    src={{ item.vol }}
    fstype=ext4
    state=mounted
  with_items:
    - { dir: '/data/1', vol: '/dev/sdb' }  
    - { dir: '/data/2', vol: '/dev/sdc' }  
    - { dir: '/data/3', vol: '/dev/sdd' }  
    - { dir: '/data/4', vol: '/dev/sde' }  
    - { dir: '/data/5', vol: '/dev/sdf' }  
    - { dir: '/data/6', vol: '/dev/sdg' }
  when: dfs_internap  
  tags:
    - hadoop
    - hdfs_datanode

- name: create data directories
  file:
    path={{ item }}
    state=directory
    mode=0755
    owner={{ hdfs_user }}
    group={{ hdfs_group }}
  with_items:
    - "{{ dfs_datanode_data_dir }}"
  tags:
    - hadoop
    - hdfs_datanode

- name: copy supervisord config
  template:
    src: hadoop-datanode-supervisord.conf.j2
    dest: "{{ supervisord_programs_dir }}/hadoop-datanode-supervisord.conf"
    mode: 0644
  notify:
    - reread supervisord
    - restart hdfs datanode
    - wait for hdfs datanode port
  tags: hadoop

- name: add datanode to supervisord
  supervisorctl:
    name: hadoop-hdfs-datanode
    state: present
  tags: hadoop


