---

- name: create data directories
  file:
    path={{ item }}
    state=directory
    mode=0755
    owner={{ hdfs_user }}
    group={{ hdfs_group }}
  with_items:
    - "{{ dfs_datanode_data_dir }}"
  tags:
    - hadoop
    - hdfs_datanode

- name: add jmx datanode environment variables
  set_fact:
    hdfs_env_vars: >
      HADOOP_NAMENODE_OPTS="-Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.authenticate={{ jmx_datanode_options.authenticate|lower }}
      -Dcom.sun.management.jmxremote.ssl={{ jmx_datanode_options.ssl|lower}}
      -Dcom.sun.management.jmxremote.port={{ jmx_datanode_options.port }}",
      {{ hdfs_env_vars }}
  when: jmx_datanode_options.enabled
  tags: hadoop-test

- name: copy supervisord config
  template:
    src: hadoop-datanode-supervisord.conf.j2
    dest: "{{ supervisord_programs_dir }}/hadoop-datanode-supervisord.conf"
    mode: 0644
  notify:
    - reread supervisord
    - restart hdfs datanode
    - wait for hdfs datanode port
  tags: hadoop

- name: add datanode to supervisord
  supervisorctl:
    name: hadoop-hdfs-datanode
    state: present
  tags: hadoop


