---
# ------------------------------ Common roles -------------------------------

- name: Run common role
  hosts: all
  roles:
    - common
  tags:
    - site-common

# ------------------------------ Customize Internap ------------------------

- name: Run Internap customize
  hosts: internap
  roles:
    - internap-customize
  tags: internap-customize
  strategy: free

# ----------------------------- Add users -----------------------------------

- hosts: all
  roles:
    - add-users
  tags: site-add-users

- name: Run virtualenv role
  hosts: all
  roles:
    - virtualenv
  tags: virtual-env

- name: Run miniconda role
  hosts: all
  roles:
    - miniconda
  tags: miniconda

# -------------------------- Zookeeper and Kafka -----------------------------
- name: Run zookeeper role
  hosts: zookeeper-nodes
  vars:
   - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ zookeeper ]
  tags:
    - site-zookeeper
    - deps-kafka
    - deps-storm
    - deps-hadoop
    - deps-hbase
    - deps-spark
    - deps-scrapy-cluster

- name: Run kafka role
  hosts: kafka-nodes
  vars:
   - kafka_host_list: "{{ groups['kafka-nodes'] }}"
   - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ kafka ]
  tags:
    - site-kafka
    - deps-kafka
    - deps-scrapy-cluster

# ------------------------------ ELK stack ------------------------------------
- name: Run elasticsearch master role
  hosts: elasticsearch-master-nodes
  vars:
   - elasticsearch_host_list: "{{ groups['elasticsearch-nodes'] }}"
   - elasticsearch_is_master: "true"
  roles: [ elasticsearch ]
  tags:
    - site-elasticsearch
    - ELK
    - deps-pulse

- name: Run elasticsearch data role
  hosts: elasticsearch-data-nodes
  vars:
   - elasticsearch_host_list: "{{ groups['elasticsearch-nodes'] }}"
   - elasticsearch_is_data: "true"
  roles: [ elasticsearch ]
  tags:
    - site-elasticsearch
    - ELK
    - deps-pulse

- name: Run elasticsearch client role
  hosts: elasticsearch-client-nodes
  vars:
   - elasticsearch_host_list: "{{ groups['elasticsearch-nodes'] }}"
   - elasticsearch_is_client: "true"
  roles: [ elasticsearch ]
  tags:
    - site-elasticsearch
    - ELK
    - deps-pulse

- name: Run logstash role
  hosts: logstash-nodes
  roles: [ logstash ]
  tags:
    - site-logstash
    - ELK

- name: Run Kibana4 role
  hosts: kibana-node
  roles: [ kibana4 ]
  tags:
    - site-kibana
    - ELK
    - deps-pulse

# --------------------------- Scraper services -------------------------------
- name: Run redis role
  hosts: redis-nodes
  roles: [ redis ]
  tags:
    - site-redis
    - deps-scrapy-cluster
    - scrapy-services

- name: Run tor role
  hosts: tor-proxy
  roles: [ tor ]
  tags:
    - site-tor
    - scrapy-services

# --------------------------- Scrapy Cluster ---------------------------------
- name: Run Scrapy Cluster Crawler
  hosts: scrapy-cluster-crawler-nodes
  vars:
    - sc_is_crawler: True
  roles: [ scrapy-cluster ]
  tags:
    - site-scrapy-cluster
    - deps-scrapy-cluster

- name: Run Scrapy Cluster Kafka Monitor
  hosts: scrapy-cluster-kafka-monitor-node
  vars:
    - sc_is_kafka_monitor: True
  roles: [ scrapy-cluster ]
  tags:
    - site-scrapy-cluster
    - deps-scrapy-cluster

- name: Run Scrapy Cluster Redis Monitor
  hosts: scrapy-cluster-redis-monitor-node
  vars:
    - sc_is_redis_monitor: True
  roles: [ scrapy-cluster ]
  tags:
    - site-scrapy-cluster
    - deps-scrapy-cluster

# ------------------------------- Scrapy Indexers ----------------------------
- name: Run scrapy-indexer role (infrastructure)
  hosts: scrapy-indexer-nodes
  roles: [ scrapy-indexer ]
  tags:
    - site-scrapy-indexer

# -------------------------------- Storm -------------------------------------

- name: Run Storm Nimbus role
  hosts: storm-nimbus-node
  vars:
    - storm_nimbus_enabled: true
    - nimbus_host: "{{ groups['storm-nimbus-node'][0] }}"
    - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ storm ]
  tags:
    - site-storm
    - deps-storm

- name: Run Storm UI role
  hosts: storm-ui-node
  vars:
    - storm_ui_enabled: true
    - nimbus_host: "{{ groups['storm-nimbus-node'][0] }}"
    - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ storm ]
  tags:
    - site-storm
    - deps-storm

- name: Run Storm supervisor role
  hosts: storm-supervisor-nodes
  vars:
    - storm_supervisor_enabled: true
    - storm_logviewer_enabled: true
    - nimbus_host: "{{ groups['storm-nimbus-node'][0] }}"
    - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ storm ]
  tags:
    - site-storm
    - deps-storm

- name: Storm Configuration Changed Fact Reset
  hosts: storm-nodes
  tasks:
    - set_fact: storm_config_changed=false
  tags:
    - site-storm
    - deps-storm

# --------------------------------- Hadoop -----------------------------------
- name: HDFS Namenode
  hosts: hadoop-namenode-node
  vars:
    - hdfs_namenode_enabled: true
    - yarn_resourcemanager_enabled: true
    - yarn_historyserver_enabled: true
    - mapreduce_historyserver_enabled: true
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_resourcemanager_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_historyserver_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
  roles: [ hadoop ]
  tags:
    - site-hadoop
    - deps-hadoop
    - deps-hbase
    - deps-spark

- name: HDFS Datanodes
  hosts: hadoop-datanode-nodes
  vars:
    - hdfs_datanode_enabled: true
    - yarn_nodemanager_enabled: true
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_resourcemanager_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_historyserver_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
  roles: [ hadoop ]
  tags:
    - site-hadoop
    - deps-hadoop
    - deps-hbase
    - deps-spark

- name: HDFS Secondary Namenode
  hosts: hadoop-secondary-namenode-node
  vars:
    - hdfs_secondary_namenode_enabled: true
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_resourcemanager_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_historyserver_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
  roles: [ hadoop ]
  tags:
    - site-hadoop
    - deps-hadoop
    - deps-hbase
    - deps-spark

- name: Hadoop Configuration Changed Fact Reset
  hosts: hadoop-nodes
  tasks:
    - set_fact: hadoop_config_changed=false
  tags:
    - site-hadoop
    - deps-hadoop
    - deps-hbase
    - deps-spark

# --------------------------------- HBase ------------------------------------
- name: HBase Master Node
  hosts: hbase-master-node
  vars:
    - hbase_master_enabled: true
    - hbase_rest_enabled: true
    - hbase_master_host: "{{ groups['hbase-master-node'][0] }}"
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ hbase ]
  tags:
    - site-hbase
    - deps-hbase

- name: HBase Region Servers
  hosts: hbase-regionserver-nodes
  vars:
    - hbase_regionserver_enabled: true
    - hbase_thriftserver_enabled: true
    - hbase_master_host: "{{ groups['hbase-master-node'][0] }}"
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - zookeeper_host_list: "{{ groups['zookeeper-nodes'] }}"
  roles: [ hbase ]
  tags:
    - site-hbase
    - deps-hbase

- name: HBase Configuration Changed Fact Reset
  hosts: hbase-nodes
  tasks:
    - set_fact: hbase_config_changed=false
  tags:
    - site-hbase
    - deps-hbase

# --------------------------------- Spark ------------------------------------
# Requires Hadoop and HDFS

- name: Spark Master Nodes
  hosts: spark-master-node
  vars:
    - spark_master_enabled: true
    - spark_worker_enabled: false
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_historyserver_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
  roles: [ spark ]
  tags:
    - site-spark
    - deps-spark

- name: Spark Workers
  hosts: spark-worker-nodes
  vars:
    - spark_master_enabled: false
    - spark_worker_enabled: true
    - dfs_namenode_host: "{{ groups['hadoop-namenode-node'][0] }}"
    - yarn_historyserver_hostname: "{{ groups['hadoop-namenode-node'][0] }}"
  roles: [ spark ]
  tags:
    - site-spark
    - deps-spark

- name: Spark Configuration Changed Fact Reset
  hosts: spark-nodes
  tasks:
    - set_fact: spark_config_changed=false
  tags:
    - site-spark
    - deps-spark

# ---------------------------------- Docker Engine ---------------------------

- name: Docker Engine
  hosts: docker-engine
  roles: [ docker-engine ]
  tags:
    - site-docker-engine
    - deps-pulse-docker

# ---------------------------------- MySQL -----------------------------------

- name: MySQL
  hosts: mysql-node
  roles: [ mysql ]
  tags:
    - mysql
    - deps-pulse
    - deps-pulse-docker

# ---------------------------------- Pulse -----------------------------------

- name: Pulse UI Node Infrastructure
  hosts: pulse-ui-node
  roles: [ pulse-ui ]
  tags:
    - site-pulse
    - deps-pulse
    - site-pulse-docker
    - deps-pulse-docker

- name: Pulse Docker Infrastructure
  hosts: docker-engine
  vars_files:
    - roles/elasticsearch/defaults/main.yml
    - roles/kibana4/defaults/main.yml
  roles: [ pulse-docker ]
  tags:
    - site-pulse-docker
    - deps-pulse-docker

# ---------------------------------- Neo4j --------------------------------

- name: Neo4j
  hosts: neo4j-node
  roles: [ neo4j ]
  tags:
    - site-neo4j

# ---------------------------------- Tangelo --------------------------------

- name: Tangelo
  hosts: tangelo-node
  roles: [ tangelo ]
  tags:
    - site-tangelo
