---
# The seed urls to index
urllist:
# A small subset of all of the myproviderguide escort urls
# - http://myproviderguide.com/auburn/escorts
 - http://myproviderguide.com/washington-dc/escorts

# The regex to pull ad links out fo the indexed page
findadregex: http://myproviderguide.com/\S+/escorts/\d+

# Needed or we will get banned (in seconds)
downloaddelay: 10

# the redis hash key to manage duplicate urls and refresh alerts
# this should be the same across indexers doing the same site
rediskey: indexer-myproviderguide
