---
- name: create gnip monitor install directory
  file:
    path={{ gnip_monitor_install_dir }}/
    state=directory
    mode=0744
  tags: gnip-monitor

- name: create gnip monitor log directory
  file:
    path={{ gnip_monitor_log_dir }}/
    state=directory
    mode=0755
  tags: gnip-monitor

- name: check for existing gnip monitor install
  stat: path={{ gnip_monitor_install_dir }}/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}
  register: gnipmonitor
  tags: gnip-monitor

- name: download gnip monitor
  get_url:
    validate_certs=no
    url={{ repository_infrastructure }}/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}.tgz
    dest=/tmp/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}.tgz
    mode=0644
  when: gnipmonitor.stat.isdir is not defined
  tags: gnip-monitor

- name: extract gnip monitor
  unarchive:
    src=/tmp/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}.tgz
    dest={{ gnip_monitor_install_dir }}/
    copy=no
  when: gnipmonitor.stat.isdir is not defined
  tags: gnip-monitor

- name: delete temporary gnip monitor file
  file:
    path=/tmp/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}.tgz
    state=absent
  ignore_errors: yes
  tags: gnip-monitor

- name: create gnip monitor symlink
  file:
    path={{ gnip_monitor_install_dir }}/default
    state=link
    src={{ gnip_monitor_install_dir }}/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}
  tags: gnip-monitor

- name: install settings file
  template:
    src=settings.py.j2
    dest={{ gnip_monitor_install_dir }}/{{ gnip_monitor_name }}-{{ gnip_monitor_version }}/settings.py
    mode=0644
  tags:
    - gnip-monitor
    - settings

- name: Install Miniconda packages
  shell: "{{ miniconda_install_dir|default('/opt/miniconda') }}/bin/conda install {{ item }} --yes"
  with_items:
    - pip
  tags:
    - gnip-monitor
    - miniconda

- name: Miniconda pip install  packages
  shell: "{{ miniconda_install_dir|default('/opt/miniconda') }}/bin/pip install {{ item }}"
  with_items:
    - kafka-python
    - elasticsearch
    - numpy
  tags:
    - gnip-monitor
    - miniconda

- name: copy supervisord config
  template:
    src={{ gnip_monitor_name }}-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/{{ gnip_monitor_name }}-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: gnip-monitor

- name: copy logstash templates
  template:
    src="{{item}}.json.j2"
    dest="{{logstash_template_dir}}/{{item}}.json"
    mode=0644
  with_items:
    - "{{gnip_monitor_prod_name}}"
    - "{{gnip_monitor_dev_name}}"

- name: copy logstash configs
  template:
    src="{{ item }}.conf.j2"
    dest="{{ logstash_conf_dir }}/{{ item }}.conf"
    mode=0644
  with_items:
    - "{{ gnip_monitor_prod_name}}-logstash"
    - "{{ gnip_monitor_dev_name }}-logstash"
  notify:
    - restart logstash
  tags:
    - gnip-monitor
    - logstash
