---
- name: RedHat - Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache
  tags:
    - apache2

- name: RedHat - Configure Apache directory.
  replace:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "^<Directory \"/var/www/html\">"
    replace: "<Directory \"{{ apache_document_root }}\">"
  notify: restart apache
  tags:
    - apache2

- name: RedHat - Add Apache vhosts configuration.
  template:
    src: "vhosts-{{ apache_vhosts_version }}.conf.j2"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
  tags:
    - apache2

