---
- name: Debian - Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Debian - Ensure Apache is installed.
  apt: 
    name: "{{ item }}"
    state: installed
  with_items: apache_packages
  tags:
    - apache2
