---
- name: ensure supervisord is installed
  pip:
    name={{ item }}
    state=latest
  with_items:
    - supervisor
    - supervisor-wildcards
  tags: supervisord

- name: ensure directories are created
  file:
    state=directory
    dest={{ item }}
    mode=0755
  with_items:
    - "{{ supervisord_log_dir }}"
    - "{{ supervisord_programs_dir }}"
  tags: supervisord

- name: setup configuration
  template:
    src=supervisord.conf.j2
    dest=/etc/supervisord.conf
  tags: supervisord

- name: setup CentOS supervisord service script
  copy:
    src=supervisord_centos
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "RedHat"

- name: setup Ubuntu supervisord service script
  copy:
    src=supervisord_ubuntu
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "Debian"

- name: ensure supervisord is running
  service:
    name: supervisord
    state: started
  tags: supervisord

- name: Set fact supervisord_has_run
  set_fact:
    supervisord_has_run: true
