---
- block:
    - name: Install logrotate
      package:
        name: logrotate
        state: present

    - name: Setup logrotate.d scripts
      template:
        src: logrotate.d.j2
        dest: "{{ logrotate_conf_dir }}{{ item.name }}"
      with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined and logrotate_scripts|length > 0
