---
- name: restart elasticsearch master
  supervisorctl:
    name=elasticsearch-master
    state=restarted
  when: elasticsearch_is_master

- name: restart elasticsearch data
  supervisorctl:
    name=elasticsearch-data
    state=restarted
  when: elasticsearch_is_data

- name: restart elasticsearch client
  supervisorctl:
    name=elasticsearch-client
    state=restarted
  when: elasticsearch_is_client

- name: restart elasticsearch master-data
  supervisorctl:
    name=elasticsearch-master-data
    state=restarted
  when: (elasticsearch_is_data=="true" and elasticsearch_is_master=="true")