---

- name: create kafka directories
  file:
    path={{ item }}
    state=directory
    mode=0744
  with_items:
    - "{{ kafka_install_dir }}"
    - "{{ kafka_data_log_dir }}"
  tags: kafka

- name: Configuring group
  group:
    name: "{{ kafka_group }}"
  tags: kafka

- name: create kafka user and group
  user:
    name={{ kafka_user }}
    group={{ kafka_group }}
    shell=/usr/sbin/nologin
    createhome=no
  tags: kafka

- name: check for existing install
  stat: path={{ kafka_install_dir }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}
  register: kafka
  tags: kafka

- name: download kafka
  get_url:
    url="{{ repository_infrastructure }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest="/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    mode=0644
    validate_certs=no
  when: kafka.stat.isdir is not defined
  tags: kafka

- name: extract kafka
  unarchive:
    src="/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest={{ kafka_install_dir }}
    copy=no
  when: kafka.stat.isdir is not defined
  tags: kafka

- name: delete temporary kafka file
  file:
    path="/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    state=absent
  ignore_errors: yes
  tags: kafka

- name: create kafka symlink
  file:
    path="{{ kafka_install_dir }}/default"
    state=link
    src="{{ kafka_install_dir }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
  tags: kafka

- name: configure kafka brokers
  template:
    src=server.properties.j2
    dest={{ kafka_config_dir }}/server.properties
    mode=0644
  notify:
    - restart kafka
  tags: kafka

- name: configure log4j
  template:
    src=log4j.properties.j2
    dest={{ kafka_config_dir }}/log4j.properties
    mode=0644
  notify:
    - restart kafka
  tags: kafka

- name: configure kafka consumer
  template:
    src=consumer.properties.j2
    dest={{ kafka_config_dir }}/consumer.properties
    mode=0644
  notify:
    - restart kafka
  tags: kafka

- name: copy supervisord config
  template:
    src=kafka-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/kafka-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: kafka

- name: set up aliases
  lineinfile:
    dest: "/root/.bashrc"
    line: "export KAFKA={{ kafka_install_dir }}/default"
  tags: env

- name: set owner and group of kafka directory and files
  file:
    path={{ kafka_install_dir }}
    state=directory
    recurse=yes
    owner={{ kafka_user }}
    group={{ kafka_group }}
  tags: kafka

# - cron: name="clear old kafka app logs" job="find /opt/kafka/default/logs -mtime +7 -exec rm {} \; > /dev/null" minute="0"
