---
# file: roles/pip/tasks/main.yml

- name: yum install python-pip
  yum:
    name: python-pip
    state: present
  tags: pip
  when: ansible_os_family == "RedHat"

- name: apt install python-pip
  apt:
    name: python-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: pip
  when: ansible_os_family == "Debian"

- name: configure pip to use the local repository
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
    mode: 0775
  tags: pip

- name: pip environment configuration
  lineinfile:
    dest: /etc/environment
    line: "export PIP_CONFIG_FILE=/etc/pip.conf"
  tags: pip

- name: Set fact pip_has_run
  set_fact:
    pip_has_run: true
