---

# Defaults...
oozie_version: 4.2.0
oozie_install_dir: /opt/oozie
oozie_user: oozie
oozie_group: oozie
oozie_pom_xmlconfig: "{{ oozie_install_dir }}/default/pom.xml"


repository_infrastructure: "{{ apache_mirror }}/oozie/{{ oozie_version }}"
extjs_download_url: "http://archive.cloudera.com/gplextras/misc/ext-2.2.zip"

oozie_external_vars:
  hdfs_version: "{{ hdfs_version | default('2.5.2') }}"
  spark_version: "{{ spark_version | default('1.6.1') }}"
  hbase_version: "{{ hbase_version | default('1.1.3') }}"
  hdfs_conf_dir: "{{ hdfs_conf_dir | default('/opt/hadoop/default/etc/hadoop') }}"
  hdfs_user: "{{ hdfs_user | default('hadoop') }}"
  hbase_install_dir: "{{ hbase_install_dir | default('/opt/hbase') }}"
  dfs_namenode_port: "{{ dfs_namenode_port | default(8020) }}"
