---

- name: Create 'sudo' group
  group: name=sudo state=present
  tags:
  - sudo
  - add-users
- name: Make sure passwordless sudo is enabled for users with sudo
  sudo: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  tags:
    - sudo
    - add-users

- include: techops.yml
  when: people == "techops"
  tags:
    - techops-users
    - add-users

- include: dev.yml
  when: people == "dev"
  tags:
    - dev-users
    - add-users

- include: third-party.yml
  when: people == "third_party"
  tags:
    - hadoop
    - hdfs_namenode
