---
# Note the password for logging in is
# username: neo4j
# password: neo4jisgreat
# there is a fancy SHA hash with salt, just issue the command
# :server change-password
# and copy the `auth` file back over to change the password

neo4j_package: community
neo4j_version: 2.3.2

neo4j_user: neo4j
neo4j_group: neo4j
neo4j_install_dir: /opt/neo4j
neo4j_server_database_location: /data/graph.db

# Let the webserver only listen on the specified IP. Default is localhost (only
# accept local connections). Uncomment to allow any connection. Please see the
# security section in the neo4j manual before modifying this.
neo4j_server_webserver_address: 0.0.0.0

neo4j_server_webserver_port: 7474
neo4j_server_webserver_https_enabled: false
neo4j_server_webserver_https_port: 7473
neo4j_server_webserver_https_cert_location: conf/ssl/snakeoil.cert
neo4j_server_webserver_https_key_location: conf/ssl/snakeoil.key
neo4j_server_webserver_https_keystore_location: data/keystore

neo4j_online_backup_enabled: true
neo4j_online_backup_host: 127.0.0.1
neo4j_online_backup_port: 6362

neo4j_wrapper_java_initmemory: 512
neo4j_wrapper_java_maxmemory: 2048
neo4j_file_limits: 40000

neo4j_server_webadmin_rrdb_location: data/rrd
neo4j_server_webadmin_data_uri: /db/data/
neo4j_server_webadmin_management_uri: /db/manage/
neo4j_server_db_tuning_properties: conf/neo4j.properties
neo4j_server_manage_console_engines: shell
neo4j_server_database_mode: SINGLE

neo4j_server_http_log_enabled: false
neo4j_server_http_log_config: conf/neo4j-http-logging.xml

neo4j_stdout_logfile_maxbytes: 50MB
neo4j_stderr_logfile_maxbytes: 50MB

repository_infrastructure:  "http://neo4j.com/artifact.php?name=neo4j-community-{{ neo4j_version }}-unix.tar.gz"