---
- name: Create slow query log file (if configured).
  shell: "touch {{ mysql_slow_query_log_file }} creates={{ mysql_slow_query_log_file }}"
  when: mysql_slow_query_log_enabled
  tags:
    - mysql

- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644
  when: mysql_slow_query_log_enabled
  tags:
    - mysql

- name: RedHat - Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
  when: ansible_os_family == 'RedHat'
  tags:
    - mysql
