---

- name: Format AWS volume if it isn't formatted
  filesystem:
    fstype: ext4
    dev: "{{ data_volume }}"
  tags:
    - aws

- name: Mounting attached ec2 volume if deploying in amazon
  mount:
    name: /data
    src: "{{ data_volume }}"
    fstype: ext4
    opts: rw
    state: mounted
  tags:
    - aws

- name: Change permissions on data partition
  file:
    path: /data
    state: touch
    mode: 0777
  tags:
    - aws
