---

kafka_scala_version: 2.11
kafka_version: 0.10.1.1

kafka_install_dir: /opt/kafka
kafka_config_dir: /opt/kafka/default/config
kafka_log_dir: /var/log/kafka
kafka_log_rolling_retention_count: 10
kafka_log_rolling_max_size: 25MB

kafka_data_dir:
  - "/opt/kafka"
kafka_data_log_dir:
  - "/opt/kafka/topic-logs"

kafka_user: kafka
kafka_group: kafka
kafka_port: 9092
kafka_jmx_port: 9999
kafka_message_max: 10000000
kafka_consumer_message_max: 16777216
kafka_num_partitions: 3
kafka_replication_factor: 3
kafka_log_retention_hours: 168
kafka_num_network_threads: 8
kafka_num_io_threads: 8
kafka_num_replica_fetchers: 6
kafka_zookeeper_connection_timeout: 6000
kafka_heap: 1G

repository_infrastructure: "{{ apache_mirror }}/kafka/{{ kafka_version }}"
