---

- name: yum install java 
  yum: 
    name=jdk-{{ java_version }}
    state=present
  tags: java

- name: java system environment configuration
  copy:
    src=java.sh
    dest=/etc/profile.d/java.sh
    owner=0
    group=0
    mode=0755
  tags: java

- name: Set JAVA_HOME ansible fact
  set_fact:
    java_home=/usr/java/default
  tags: java

- name: Create Ansible facts.d directory
  file:
    state=directory
    dest=/etc/ansible/facts.d
    owner=0
    group=0
    mode=0755
  tags: java

- name: Install java facts
  template:
    src=facts.j2
    dest=/etc/ansible/facts.d/java.fact
    owner=0
    group=0
    mode=0644
  tags: java

- name: Re-read facts
  setup:
    filter=ansible_local
  tags: java