---
- name: restart ntp
  service:
    name={{ ntp_daemon }}
    state=restarted

- name: synchronize clock
  shell: "service {{ ntp_daemon }} stop; ntpdate {{ ntp_server_host }}; service {{ ntp_daemon }} start"
  when: inventory_hostname != ntp_server_host

- name: update resolvconf
  command: resolvconf -u
