---
- name: Curl legacy DB setup
  command: /usr/bin/curl {{ inventory_hostname }}/{{ pulse_name }}/install/resetup_db/
  when: pulse_db_legacy_setup
  tags: pulse-ui-db-app

- name: Retrieve passwd
  shell: cat {{ pulse_install_dir }}/pulse-{{ pulse_version }}/install.pw
  register: passwd
  when: not pulse_db_legacy_setup
  tags: pulse-ui-db-app

- name: Show passwd
  debug: msg="The passwd is {{ passwd.stdout }}"
  when: not pulse_db_legacy_setup
  tags: pulse-ui-db-app

- name: Curl DB setup
  command: /usr/bin/curl --request POST --url {{ inventory_hostname }}/{{ pulse_name }}/install/setup_website --data "installpw={{ passwd.stdout }}" --data "install_database=true"
  when: not pulse_db_legacy_setup
  tags: pulse-ui-db-app

- name: Move titan sql script over
  template:
    src=setup_titan.sql.j2
    dest=/tmp/setup_titan.sql
  tags: pulse-ui-db-app

- name: Setup mysql titan user
  mysql_db:
    name={{ pulse_db_name }}
    state=import
    target=/tmp/setup_titan.sql
  tags: pulse-ui-db-app

- name: Remove titan sql script
  file:
    path=/tmp/setup_titan.sql
    state=absent
  ignore_errors: yes
  tags: pulse-ui-db-app

- name: Move mmr setup sql script over
  template:
    src=setup_mmr.sql.j2
    dest=/tmp/setup_mmr.sql
  tags: pulse-ui-db-app

- name: Setup default mmr directory in the Pulse instance
  mysql_db:
    name={{ pulse_db_name }}
    state=import
    target=/tmp/setup_mmr.sql
  tags: pulse-ui-db-app

- name: Remove mmr setup sql script
  file:
    path=/tmp/setup_mmr.sql
    state=absent
  ignore_errors: yes
  tags: pulse-ui-db-app

