---
- name: set up spark history directory in hdfs
  shell: "{{ item }}"
  with_items:
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}/{{ spark_history_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -chown -R spark:spark {{ spark_hdfs_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -chmod 1777 {{ spark_hdfs_dir }}/{{ spark_history_dir }}"
  environment:
    JAVA_HOME: "{{ java_home }}"
  become: yes
  become_user: "{{ hdfs_user|default('hadoop') }}"
  run_once: true
  delegate_to: "{{ dfs_namenode_host }}"
  when: inventory_hostname != dfs_namenode_host
  tags: spark

- name: set up spark history directory in hdfs (same host)
  shell: "{{ item }}"
  with_items:
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}/{{ spark_history_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -chown -R spark:spark {{ spark_hdfs_dir }}"
    - "{{ hdfs_exe_dir|default('/opt/hadoop/default/bin') }}/hadoop fs -chmod 1777 {{ spark_hdfs_dir }}/{{ spark_history_dir }}"
  environment:
    JAVA_HOME: "{{ java_home }}"
  become: yes
  become_user: "{{ hdfs_user|default('hadoop') }}"
  run_once: true
  when: inventory_hostname == dfs_namenode_host
  tags: spark

- name: copy supervisord config
  template:
    src=spark-master-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/spark-master-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
    - restart spark master
  tags: spark
