---
- block:
  - name: set up spark history (1/4)
    shell: "{{ hdfs_exe_dir }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}"

  - name: set up spark history (2/4)
    shell: "{{ hdfs_exe_dir }}/hadoop fs -mkdir -p {{ spark_hdfs_dir }}/{{ spark_history_dir }}"

  - name: set up spark history (3/4)
    shell: "{{ hdfs_exe_dir }}/hadoop fs -chown -R spark:spark {{ spark_hdfs_dir }}"

  - name: set up spark history (4/4)
    shell: "{{ hdfs_exe_dir }}/hadoop fs -chmod 1777 {{ spark_hdfs_dir }}/{{ spark_history_dir }}"

  become: yes
  become_user: "{{ hdfs_user }}"
  tags: spark

- name: copy supervisord config
  template:
    src=spark-master-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/spark-master-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
    - restart spark master
  tags: spark
