---
- name: RedHat - Update postfix to the latest version (if extra repositories enabled).
  yum: "name=postfix state=latest enablerepo={{ mysql_enablerepo }}"
  when: mysql_enablerepo != ""
  tags:
    - mysql

- name: RedHat - Ensure MySQL Python libraries are installed.
  yum: "name=MySQL-python state=installed enablerepo={{ mysql_enablerepo }}"
  tags:
    - mysql

- name: RedHat - Ensure MySQL packages are installed.
  yum: "name={{ item }} state=installed enablerepo={{ mysql_enablerepo }}"
  with_items: mysql_packages
  tags:
    - mysql
