---
# file: roles/common/tasks/main.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: ntp.yml
  when: ntp_server_host != ''
  tags:
    - common
    - ntp

- include: swap.yml
  when: swap_run
  tags:
    - common
    - swap_file

- include: resolv-conf.yml
  when: ansible_os_family == 'Debian'
  tags:
    - common
    - resolvconf

- include: sshd.yml
  tags:
    - common
    - sshd

- name: Set fact common_has_run
  set_fact:
    common_has_run: true
