---

- name: update apt-get cache
  apt: update-cache=yes
  tags: common

- name: install baseline packages
  apt:
    name={{ item }}
    state=latest
  with_items:
    - bash
    - openssh-server
    - wget
    - zip
    - unzip
    # used for scrapy, gandalf, and general python work
    - python-lxml
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - byobu
    - mosh
    - mtr-tiny
    - vim
    - git
    - python
    - vim-scripts
    - etckeeper
    - htop
    - iotop
    - sudo
    - rcconf
    - logwatch
    - telnet
    - dnsutils
    - unattended-upgrades
    - gcc
    - libc6-dev
    - make
    - zlib1g-dev
    - e2fslibs-dev
  tags: common

- name: remove hostname loopback
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.1\.1\s+{{ inventory_hostname }}.*$"
    state=absent
  tags: common
  when: remove_hostname_loopback
