---

- name: Configuring group
  group:
    name: "{{ oozie_group }}"
  tags:
    - oozie

- name: Configuring user
  user:
    name: "{{ oozie_user }}"
    group: "{{ oozie_group }}"
    shell: /bin/bash
    createhome: yes
  tags:
    - oozie

- name: create install directory
  file:
    path={{ item }}
    state=directory
    mode=0755
    owner={{ oozie_user }}
    group={{ oozie_group }}
  with_items:
    - "{{ oozie_install_dir }}"
  tags:
    - oozie

- name: check for existing install
  stat: path="{{ oozie_install_dir }}/oozie-{{ oozie_version }}"
  register: oozie
  tags: oozie

- name: download oozie
  get_url:
    url: "{{ repository_infrastructure }}/oozie-{{ oozie_version }}.tar.gz"
    dest: /tmp/oozie-{{ oozie_version }}.tgz
    mode: 0644
    validate_certs: no
  when: oozie.stat.isdir is not defined
  tags: oozie

- name: extract oozie
  unarchive:
    src: /tmp/oozie-{{ oozie_version }}.tgz
    dest: "{{ oozie_install_dir }}"
    copy: no
    owner: "{{ oozie_user }}"
    group: "{{ oozie_group }}"
  when: oozie.stat.isdir is not defined
  tags: oozie

- name: delete temporary oozie file
  file:
    path: /tmp/oozie-{{ oozie_version }}.tgz
    state: absent
  ignore_errors: yes
  tags: oozie

- name: create oozie symlink
  file:
    path: "{{ oozie_install_dir }}/default"
    state: link
    src: "{{ oozie_install_dir }}/oozie-{{ oozie_version }}"
  tags: oozie

#- name: restart oozie to apply configuration changes
#  set_fact: oozie_config_changed={{ oozie_config.changed or (oozie_config_changed is defined and oozie_config_changed) }}
#  notify:
#    - restart oozie
#    - wait for oozie port
#  changed_when: oozie_config_changed
#  tags: oozie
