---
# The seed urls to index
urllist:
# DYNAMICLY GENERATED URLS
  - http://www.eros.com/utah/sections/utah_escorts.htm
  - http://www.eros.com/texas/houston/sections/houston_escorts.htm
  - http://www.eros.com/texas/dallas/sections/dallas_escorts.htm
  - http://www.eros.com/texas/austin/sections/austin_escorts.htm
  - http://www.eros.com/tennessee/nashville/sections/nashville_escorts_available_now.htm
  - http://www.eros.com/tennessee/memphis/sections/memphis_escorts.htm
  - http://www.eros.com/rhode_island/providence/sections/providence_escorts_available_now.htm
  - http://www.eros.com/pennsylvania/pittsburgh/sections/pittsburgh_escorts_available_now.htm
  - http://www.eros.com/pennsylvania/philadelphia/sections/philadelphia_escorts.htm
  - http://www.eros.com/oregon/portland/sections/portland_escorts_available_now.htm
  - http://www.eros.com/oklahoma/sections/oklahoma_escorts.htm
  - http://www.eros.com/ohio/sections/ohio_escorts.htm
  - http://www.eros.com/carolinas/sections/carolina_escorts.htm
  - http://www.eros.com/new_york/new_york/sections/new_york_escorts.htm
  - http://www.eros.com/new_york/buffalo/sections/buffalo_authenticated_escorts.htm
  - http://www.eros.com/new_york/albany/sections/albany_authenticated_escorts.htm
  - http://www.eros.com/wisconsin/sections/wisconsin_escorts.htm
  - http://www.eros.com/washington_dc/sections/washington_dc_escorts.htm
  - http://www.eros.com/washington/seattle/sections/seattle_escorts.htm
  - http://www.eros.com/virginia/sections/virginia_escorts.htm
  - http://www.eros.com/new_mexico/albuquerque/sections/albuquerque_gfe_escorts.htm
  - http://www.eros.com/new_jersey/sections/new_jersey_escorts.htm
  - http://www.eros.com/nevada/reno/sections/reno_authenticated_escorts.htm
  - http://www.eros.com/nevada/las_vegas/sections/las_vegas_escorts.htm
  - http://www.eros.com/nebraska/sections/nebraska_authenticated_escorts.htm
  - http://www.eros.com/missouri/st_louis/sections/st_louis_escorts.htm
  - http://www.eros.com/missouri/kansas_city/sections/kansas_city_authenticated_escorts.htm
  - http://www.eros.com/mississippi/biloxi/sections/biloxi_escorts_available_now.htm
  - http://www.eros.com/minnesota/sections/minnesota_escorts.htm
  - http://www.eros.com/michigan/sections/michigan_escorts.htm
  - http://www.eros.com/massachusetts/boston/sections/boston_escorts.htm
  - http://www.eros.com/maryland/baltimore/sections/baltimore_escorts.htm
  - http://www.eros.com/louisiana/new_orleans/sections/new_orleans_escorts.htm
  - http://www.eros.com/kentucky/louisville/sections/louisville_escorts_available_now.htm
  - http://www.eros.com/indiana/sections/indiana_escorts.htm
  - http://www.eros.com/illinois/chicago/sections/chicago_escorts.htm
  - http://www.eros.com/hawaii/sections/hawaii_escorts.htm
  - http://www.eros.com/georgia/atlanta/sections/atlanta_escorts.htm
  - http://www.eros.com/florida/tampa/sections/tampa_escorts.htm
  - http://www.eros.com/florida/north_florida/sections/north_florida_escorts.htm
  - http://www.eros.com/florida/naples/sections/naples_escorts.htm
  - http://www.eros.com/florida/miami/sections/miami_escorts.htm
  - http://www.eros.com/connecticut/hartford/sections/hartford_escorts.htm
  - http://www.eros.com/colorado/sections/colorado_escorts.htm
  - http://www.eros.com/california/san_jose/sections/san_jose_escorts.htm
  - http://www.eros.com/california/san_francisco/sections/san_francisco_escorts.htm
  - http://www.eros.com/california/san_diego/sections/san_diego_escorts.htm
  - http://www.eros.com/california/los_angeles/sections/los_angeles_escorts.htm
  - http://www.eros.com/arizona/sections/arizona_escorts.htm
  - http://www.eros.com/alabama/sections/alabama_escorts.htm

# The regex to pull pagination links out of the indexed pages
paginateregex: http://www\.eros.com/.+/sections/.+\.htm/\d+

# How many pagination pages to go deep
paginatenum: 1

# The regex to pull ad links out of the indexed page
findadregex: http://www\.eros.com/.+/files/\d+.htm

# Needed or we will get banned (in seconds)
downloaddelay: 10

# the redis hash key to manage duplicate urls and refresh alerts
# this should be the same across indexers doing the same site
rediskey: indexer-eros