---
# The seed urls to index
urllist:
# DYNAMICLY GENERATED URLS
  - myproviderguide.com/auburn/escorts/escorts
  - myproviderguide.com/birmingham/escorts/escorts
  - myproviderguide.com/dothan-al/escorts/escorts
  - myproviderguide.com/gadsden-anniston/escorts/escorts
  - myproviderguide.com/huntsville/escorts/escorts
  - myproviderguide.com/mobile-al/escorts/escorts
  - myproviderguide.com/montgomery/escorts/escorts
  - myproviderguide.com/tuscaloosa/escorts/escorts
  - myproviderguide.com/flagstaff/escorts/escorts
  - myproviderguide.com/mohave-county/escorts/escorts
  - myproviderguide.com/phoenix/escorts/escorts
  - myproviderguide.com/prescott/escorts/escorts
  - myproviderguide.com/sierra-vista/escorts/escorts
  - myproviderguide.com/tucson/escorts/escorts
  - myproviderguide.com/yuma/escorts/escorts
  - myproviderguide.com/fayetteville-ar/escorts/escorts
  - myproviderguide.com/fort-smith-ar/escorts/escorts
  - myproviderguide.com/jonesboro/escorts/escorts
  - myproviderguide.com/little-rock/escorts/escorts
  - myproviderguide.com/bakersfield/escorts/escorts
  - myproviderguide.com/chico/escorts/escorts
  - myproviderguide.com/fresno/escorts/escorts
  - myproviderguide.com/gold-country/escorts/escorts
  - myproviderguide.com/humboldt-county/escorts/escorts
  - myproviderguide.com/imperial-county/escorts/escorts
  - myproviderguide.com/inland-empire/escorts/escorts
  - myproviderguide.com/los-angeles/escorts/escorts
  - myproviderguide.com/mendocino-county/escorts/escorts
  - myproviderguide.com/merced/escorts/escorts
  - myproviderguide.com/modesto/escorts/escorts
  - myproviderguide.com/monterey-bay/escorts/escorts
  - myproviderguide.com/oakland/escorts/escorts
  - myproviderguide.com/orange-county/escorts/escorts
  - myproviderguide.com/palm-springs-ca/escorts/escorts
  - myproviderguide.com/redding/escorts/escorts
  - myproviderguide.com/sacramento/escorts/escorts
  - myproviderguide.com/san-diego/escorts/escorts
  - myproviderguide.com/san-fernando-valley/escorts/escorts
  - myproviderguide.com/san-francisco/escorts/escorts
  - myproviderguide.com/san-jose/escorts/escorts
  - myproviderguide.com/san-luis-obispo/escorts/escorts
  - myproviderguide.com/santa-barbara/escorts/escorts
  - myproviderguide.com/stockton/escorts/escorts
  - myproviderguide.com/ventura-county/escorts/escorts
  - myproviderguide.com/visalia-tulare/escorts/escorts
  - myproviderguide.com/yuba-sutter/escorts/escorts
  - myproviderguide.com/boulder/escorts/escorts
  - myproviderguide.com/colorado-springs/escorts/escorts
  - myproviderguide.com/denver/escorts/escorts
  - myproviderguide.com/fort-collins/escorts/escorts
  - myproviderguide.com/pueblo/escorts/escorts
  - myproviderguide.com/rocky-mountains/escorts/escorts
  - myproviderguide.com/hartford/escorts/escorts
  - myproviderguide.com/new-haven/escorts/escorts
  - myproviderguide.com/washington-dc/escorts/escorts
  - myproviderguide.com/delaware/escorts/escorts
  - myproviderguide.com/boca-raton/escorts/escorts
  - myproviderguide.com/daytona-beach/escorts/escorts
  - myproviderguide.com/florida-keys/escorts/escorts
  - myproviderguide.com/fort-lauderdale/escorts/escorts
  - myproviderguide.com/fort-myers/escorts/escorts
  - myproviderguide.com/gainesville/escorts/escorts
  - myproviderguide.com/jacksonville/escorts/escorts
  - myproviderguide.com/lakeland/escorts/escorts
  - myproviderguide.com/miami/escorts/escorts
  - myproviderguide.com/ocala/escorts/escorts
  - myproviderguide.com/okaloosa/escorts/escorts
  - myproviderguide.com/orlando/escorts/escorts
  - myproviderguide.com/panama-city-fl/escorts/escorts
  - myproviderguide.com/pensacola/escorts/escorts
  - myproviderguide.com/sarasota-bradenton/escorts/escorts
  - myproviderguide.com/space-coast/escorts/escorts
  - myproviderguide.com/st-augustine/escorts/escorts
  - myproviderguide.com/tallahassee/escorts/escorts
  - myproviderguide.com/tampa/escorts/escorts
  - myproviderguide.com/treasure-coast/escorts/escorts
  - myproviderguide.com/west-palm-beach/escorts/escorts
  - myproviderguide.com/athens-ga/escorts/escorts
  - myproviderguide.com/atlanta/escorts/escorts
  - myproviderguide.com/augusta/escorts/escorts
  - myproviderguide.com/brunswick-ga/escorts/escorts
  - myproviderguide.com/columbus-ga/escorts/escorts
  - myproviderguide.com/macon/escorts/escorts
  - myproviderguide.com/savannah/escorts/escorts
  - myproviderguide.com/valdosta/escorts/escorts
  - myproviderguide.com/honolulu/escorts/escorts
  - myproviderguide.com/boise/escorts/escorts
  - myproviderguide.com/twin-falls/escorts/escorts
  - myproviderguide.com/bloomington-normal/escorts/escorts
  - myproviderguide.com/carbondale/escorts/escorts
  - myproviderguide.com/champaign/escorts/escorts
  - myproviderguide.com/chicago/escorts/escorts
  - myproviderguide.com/decatur-il/escorts/escorts
  - myproviderguide.com/peoria/escorts/escorts
  - myproviderguide.com/rockford/escorts/escorts
  - myproviderguide.com/springfield-il/escorts/escorts
  - myproviderguide.com/bloomington/escorts/escorts
  - myproviderguide.com/evansville/escorts/escorts
  - myproviderguide.com/fort-wayne/escorts/escorts
  - myproviderguide.com/indianapolis/escorts/escorts
  - myproviderguide.com/muncie/escorts/escorts
  - myproviderguide.com/south-bend/escorts/escorts
  - myproviderguide.com/terre-haute/escorts/escorts
  - myproviderguide.com/ames-ia/escorts/escorts
  - myproviderguide.com/cedar-rapids/escorts/escorts
  - myproviderguide.com/des-moines/escorts/escorts
  - myproviderguide.com/dubuque/escorts/escorts
  - myproviderguide.com/iowa-city/escorts/escorts
  - myproviderguide.com/sioux-city-ia/escorts/escorts
  - myproviderguide.com/waterloo/escorts/escorts
  - myproviderguide.com/lawrence/escorts/escorts
  - myproviderguide.com/manhattan-ks/escorts/escorts
  - myproviderguide.com/topeka/escorts/escorts
  - myproviderguide.com/wichita/escorts/escorts
  - myproviderguide.com/bowling-green/escorts/escorts
  - myproviderguide.com/lexington-ky/escorts/escorts
  - myproviderguide.com/louisville/escorts/escorts
  - myproviderguide.com/baton-rouge/escorts/escorts
  - myproviderguide.com/lafayette/escorts/escorts
  - myproviderguide.com/lake-charles/escorts/escorts
  - myproviderguide.com/monroe-la/escorts/escorts
  - myproviderguide.com/new-orleans/escorts/escorts
  - myproviderguide.com/shreveport/escorts/escorts
  - myproviderguide.com/maine/escorts/escorts
  - myproviderguide.com/annapolis/escorts/escorts
  - myproviderguide.com/baltimore/escorts/escorts
  - myproviderguide.com/boston/escorts/escorts
  - myproviderguide.com/cape-cod/escorts/escorts
  - myproviderguide.com/springfield-ma/escorts/escorts
  - myproviderguide.com/worcester/escorts/escorts
  - myproviderguide.com/ann-arbor/escorts/escorts
  - myproviderguide.com/detroit/escorts/escorts
  - myproviderguide.com/flint/escorts/escorts
  - myproviderguide.com/grand-rapids/escorts/escorts
  - myproviderguide.com/jackson-mi/escorts/escorts
  - myproviderguide.com/kalamazoo/escorts/escorts
  - myproviderguide.com/lansing/escorts/escorts
  - myproviderguide.com/muskegon/escorts/escorts
  - myproviderguide.com/port-huron/escorts/escorts
  - myproviderguide.com/saginaw-midland-baycity/escorts/escorts
  - myproviderguide.com/duluth/escorts/escorts
  - myproviderguide.com/mankato/escorts/escorts
  - myproviderguide.com/minneapolis/escorts/escorts
  - myproviderguide.com/rochester-mn/escorts/escorts
  - myproviderguide.com/st-cloud/escorts/escorts
  - myproviderguide.com/biloxi/escorts/escorts
  - myproviderguide.com/hattiesburg/escorts/escorts
  - myproviderguide.com/jackson-ms/escorts/escorts
  - myproviderguide.com/joplin/escorts/escorts
  - myproviderguide.com/kansas-city/escorts/escorts
  - myproviderguide.com/saint-louis/escorts/escorts
  - myproviderguide.com/springfield-mo/escorts/escorts
  - myproviderguide.com/montana/escorts/escorts
  - myproviderguide.com/grand-island/escorts/escorts
  - myproviderguide.com/lincoln/escorts/escorts
  - myproviderguide.com/omaha/escorts/escorts
  - myproviderguide.com/las-vegas/escorts/escorts
  - myproviderguide.com/reno/escorts/escorts
  - myproviderguide.com/new-hampshire/escorts/escorts
  - myproviderguide.com/central-jersey/escorts/escorts
  - myproviderguide.com/jersey-shore/escorts/escorts
  - myproviderguide.com/north-jersey/escorts/escorts
  - myproviderguide.com/south-jersey/escorts/escorts
  - myproviderguide.com/albuquerque/escorts/escorts
  - myproviderguide.com/farmington-nm/escorts/escorts
  - myproviderguide.com/roswell/escorts/escorts
  - myproviderguide.com/santa-fe/escorts/escorts
  - myproviderguide.com/albany/escorts/escorts
  - myproviderguide.com/binghamton/escorts/escorts
  - myproviderguide.com/bronx/escorts/escorts
  - myproviderguide.com/brooklyn/escorts/escorts
  - myproviderguide.com/buffalo/escorts/escorts
  - myproviderguide.com/catskills/escorts/escorts
  - myproviderguide.com/chautauqua/escorts/escorts
  - myproviderguide.com/elmira-corning/escorts/escorts
  - myproviderguide.com/fairfield/escorts/escorts
  - myproviderguide.com/hudson-valley/escorts/escorts
  - myproviderguide.com/ithaca/escorts/escorts
  - myproviderguide.com/long-island/escorts/escorts
  - myproviderguide.com/new-york/escorts/escorts
  - myproviderguide.com/plattsburgh-adirondacks/escorts/escorts
  - myproviderguide.com/queens/escorts/escorts
  - myproviderguide.com/rochester-ny/escorts/escorts
  - myproviderguide.com/staten-island/escorts/escorts
  - myproviderguide.com/syracuse/escorts/escorts
  - myproviderguide.com/utica/escorts/escorts
  - myproviderguide.com/watertown/escorts/escorts
  - myproviderguide.com/westchester/escorts/escorts
  - myproviderguide.com/asheville/escorts/escorts
  - myproviderguide.com/boone/escorts/escorts
  - myproviderguide.com/charlotte/escorts/escorts
  - myproviderguide.com/fayetteville/escorts/escorts
  - myproviderguide.com/greensboro/escorts/escorts
  - myproviderguide.com/hickory/escorts/escorts
  - myproviderguide.com/outer-banks/escorts/escorts
  - myproviderguide.com/raleigh/escorts/escorts
  - myproviderguide.com/wilmington-nc/escorts/escorts
  - myproviderguide.com/winston-salem/escorts/escorts
  - myproviderguide.com/bismarck/escorts/escorts
  - myproviderguide.com/fargo/escorts/escorts
  - myproviderguide.com/minot/escorts/escorts
  - myproviderguide.com/north-dakota/escorts/escorts
  - myproviderguide.com/akron/escorts/escorts
  - myproviderguide.com/athens-oh/escorts/escorts
  - myproviderguide.com/cincinnati/escorts/escorts
  - myproviderguide.com/cleveland/escorts/escorts
  - myproviderguide.com/columbus/escorts/escorts
  - myproviderguide.com/dayton/escorts/escorts
  - myproviderguide.com/huntington-ashland/escorts/escorts
  - myproviderguide.com/lima/escorts/escorts
  - myproviderguide.com/mansfield/escorts/escorts
  - myproviderguide.com/parkersburg-marietta/escorts/escorts
  - myproviderguide.com/sandusky/escorts/escorts
  - myproviderguide.com/toledo/escorts/escorts
  - myproviderguide.com/youngstown/escorts/escorts
  - myproviderguide.com/lawton/escorts/escorts
  - myproviderguide.com/oklahoma-city/escorts/escorts
  - myproviderguide.com/stillwater/escorts/escorts
  - myproviderguide.com/tulsa/escorts/escorts
  - myproviderguide.com/bend/escorts/escorts
  - myproviderguide.com/corvallis/escorts/escorts
  - myproviderguide.com/eugene/escorts/escorts
  - myproviderguide.com/medford-ashland-klamath/escorts/escorts
  - myproviderguide.com/portland/escorts/escorts
  - myproviderguide.com/roseburg/escorts/escorts
  - myproviderguide.com/salem-or/escorts/escorts
  - myproviderguide.com/allentown/escorts/escorts
  - myproviderguide.com/altoona/escorts/escorts
  - myproviderguide.com/erie-pa/escorts/escorts
  - myproviderguide.com/harrisburg/escorts/escorts
  - myproviderguide.com/lancaster-pa/escorts/escorts
  - myproviderguide.com/lehigh-valley/escorts/escorts
  - myproviderguide.com/philadelphia/escorts/escorts
  - myproviderguide.com/pittsburgh/escorts/escorts
  - myproviderguide.com/poconos/escorts/escorts
  - myproviderguide.com/reading/escorts/escorts
  - myproviderguide.com/scranton/escorts/escorts
  - myproviderguide.com/williamsport/escorts/escorts
  - myproviderguide.com/york-pa/escorts/escorts
  - myproviderguide.com/providence/escorts/escorts
  - myproviderguide.com/charleston-sc/escorts/escorts
  - myproviderguide.com/columbia-sc/escorts/escorts
  - myproviderguide.com/florence-sc/escorts/escorts
  - myproviderguide.com/florence/escorts/escorts
  - myproviderguide.com/greenville/escorts/escorts
  - myproviderguide.com/hilton-head/escorts/escorts
  - myproviderguide.com/myrtle-beach/escorts/escorts
  - myproviderguide.com/south-dakota/escorts/escorts
  - myproviderguide.com/chattanooga/escorts/escorts
  - myproviderguide.com/clarksville/escorts/escorts
  - myproviderguide.com/jackson-tn/escorts/escorts
  - myproviderguide.com/knoxville/escorts/escorts
  - myproviderguide.com/memphis/escorts/escorts
  - myproviderguide.com/nashville/escorts/escorts
  - myproviderguide.com/abilene/escorts/escorts
  - myproviderguide.com/amarillo/escorts/escorts
  - myproviderguide.com/austin/escorts/escorts
  - myproviderguide.com/beaumont/escorts/escorts
  - myproviderguide.com/corpus-christi/escorts/escorts
  - myproviderguide.com/dallas/escorts/escorts
  - myproviderguide.com/denton/escorts/escorts
  - myproviderguide.com/fort-worth/escorts/escorts
  - myproviderguide.com/galveston/escorts/escorts
  - myproviderguide.com/houston/escorts/escorts
  - myproviderguide.com/killeen/escorts/escorts
  - myproviderguide.com/laredo/escorts/escorts
  - myproviderguide.com/lubbock/escorts/escorts
  - myproviderguide.com/odessa/escorts/escorts
  - myproviderguide.com/san-antonio/escorts/escorts
  - myproviderguide.com/san-marcos/escorts/escorts
  - myproviderguide.com/texarkana/escorts/escorts
  - myproviderguide.com/tyler/escorts/escorts
  - myproviderguide.com/victoria-tx/escorts/escorts
  - myproviderguide.com/waco/escorts/escorts
  - myproviderguide.com/wichita-falls/escorts/escorts
  - myproviderguide.com/logan/escorts/escorts
  - myproviderguide.com/ogden-clearfield/escorts/escorts
  - myproviderguide.com/provo/escorts/escorts
  - myproviderguide.com/salt-lake-city/escorts/escorts
  - myproviderguide.com/st-george/escorts/escorts
  - myproviderguide.com/vermont/escorts/escorts
  - myproviderguide.com/blacksburg/escorts/escorts
  - myproviderguide.com/charlottesville/escorts/escorts
  - myproviderguide.com/danville/escorts/escorts
  - myproviderguide.com/fredericksburg/escorts/escorts
  - myproviderguide.com/hampton/escorts/escorts
  - myproviderguide.com/harrisonburg/escorts/escorts
  - myproviderguide.com/lynchburg/escorts/escorts
  - myproviderguide.com/norfolk/escorts/escorts
  - myproviderguide.com/richmond/escorts/escorts
  - myproviderguide.com/roanoke/escorts/escorts
  - myproviderguide.com/virginia-beach/escorts/escorts
  - myproviderguide.com/bellingham/escorts/escorts
  - myproviderguide.com/kennewick-pasco-richland/escorts/escorts
  - myproviderguide.com/pullman/escorts/escorts
  - myproviderguide.com/seattle/escorts/escorts
  - myproviderguide.com/skagit/escorts/escorts
  - myproviderguide.com/spokane/escorts/escorts
  - myproviderguide.com/wenatchee/escorts/escorts
  - myproviderguide.com/yakima/escorts/escorts
  - myproviderguide.com/charleston-wv/escorts/escorts
  - myproviderguide.com/martinsburg/escorts/escorts
  - myproviderguide.com/morgantown/escorts/escorts
  - myproviderguide.com/wheeling-wv/escorts/escorts
  - myproviderguide.com/appleton/escorts/escorts
  - myproviderguide.com/eau-claire/escorts/escorts
  - myproviderguide.com/green-bay/escorts/escorts
  - myproviderguide.com/janesville/escorts/escorts
  - myproviderguide.com/kenosha-racine/escorts/escorts
  - myproviderguide.com/la-crosse/escorts/escorts
  - myproviderguide.com/madison/escorts/escorts
  - myproviderguide.com/milwaukee/escorts/escorts
  - myproviderguide.com/sheboygan-wi/escorts/escorts
  - myproviderguide.com/wausau/escorts/escorts
  - myproviderguide.com/wyoming/escorts/escorts

# The regex to pull pagination links out of the indexed pages
paginateregex: http://myproviderguide\.com/\S+/escorts\?page=\d+

# How many pagination pages to go deep
paginatenum: 1

# The regex to pull ad links out of the indexed page
findadregex: http://myproviderguide\.com/\S+/escorts/\d+

# Needed or we will get banned (in seconds)
downloaddelay: 10

# the redis hash key to manage duplicate urls and refresh alerts
# this should be the same across indexers doing the same site
rediskey: indexer-myproviderguide