---
- name: copy logstash template
  template:
    src: "pulse-logs-template.json"
    dest: "{{ logstash_template_dir|default('/etc/logstash.d/templates') }}/pulse-logs-template.json"
    mode: 0644
  notify:
    - restart logstash

- name: add the logstash configuration
  template:
    src: scrapy-cluster-logstash.conf.j2
    dest: "{{ logstash_conf_dir|default('/etc/logstash.d') }}/scrapy-cluster-logstash.conf"
    mode: 0644
  notify:
    - restart logstash

- name: start logstash
  supervisorctl:
    name: logstash
    state: started
