---
- name: copy logstash template
  template:
    src: "pulse-logs-template.json"
    dest: "{{ logstash_template_dir|default('/etc/logstash.d/templates') }}/pulse-logs-template.json"
    mode: 0644
  notify:
    - restart logstash

- name: add the logstash configuration
  template:
    src: scrapy-cluster-logstash.conf.j2
    dest: "{{ logstash_conf_dir|default('/etc/logstash.d') }}/scrapy-cluster-logstash.conf"
    mode: 0644
  notify:
    - restart logstash

- name: start logstash
  supervisorctl:
    name: logstash
    state: started

- name: Copy over Kibana4 backup folder
  unarchive:
    src=backup.tar
    dest=/tmp/
  run_once: true

- name: Copy over Kibana4 restore script
  copy:
    src=restore_kibana_index.sh
    dest=/tmp/
    mode=755
  run_once: true

- name: restore Kibana4 visualizations
  shell: "./restore_kibana_index.sh {{ groups['elasticsearch-nodes'][0] }} {{ elasticsearch_network_http_port|default(9200) }} backup.tar"
  args:
    chdir: "/tmp/"
  run_once: true

- name: Remove Kibana tmp files
  file:
    path=/tmp/{{ item }}
    state=absent
  with_items:
    - "restore_kibana_index.sh"
    - "backup.tar"
  run_once: true
