---
- name: restart scrapy-crawling
  shell: "supervisorctl update && supervisorctl restart {{ sc_crawling_name }}:*"
  become: yes
  become_user: root

- name: restart scrapy-kafka-monitor
  supervisorctl:
    name={{ sc_kafka_monitor_supervisor_name }}
    state=restarted

- name: restart scrapy-redis-monitor
  supervisorctl:
    name={{ sc_redis_monitor_supervisor_name }}
    state=restarted

- name: restart scrapy-indexer
  shell: "supervisorctl update && supervisorctl restart {{ sc_indexer_name }}:*"
  become: yes
  become_user: root