version: '2'

services:
  follow_0:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=0
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_0.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=hL8zsFYXvpo7yC274h269OGMm
      - CONSUMER_SECRET=xD701hZ5L7r6ZwU7WXeUEcsIQgaTtBoMuolQGJiBpHhgsKPa1y
      - ACCESS_TOKEN=3439765912-nAu6Z66xYmUAJXfgzcyOYe41YFmU6AhNscGOAym
      - ACCESS_TOKEN_SECRET=czGzMwzcFHKBxkAdJJNvz4FlwHsE0NcFzPEWgGzKuut9g
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  follow_1:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=1
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_1.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=tsKlozNvLdDU6xfHBOzpNw88e
      - CONSUMER_SECRET=1s88nBoHDl0PEEH5uRjSqLHhvabqFn0qaPlx5VbUlfPxqypTmN
      - ACCESS_TOKEN=3514842975-r8mRAN683QdZLXrpueDsHG9K8D6F0h8OLoXj0KF
      - ACCESS_TOKEN_SECRET=ZCcum9lCPV7YiYatRXb2sswYtx5tdfj5yStuxPoCmNTCB
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  follow_2:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=2
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_2.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=pGuIHNOA2Q1Jh2mlRf4BfX9kt
      - CONSUMER_SECRET=n4bosq6Cw5NDPyH3KMRGLkovCuDEAVtOpHCQJXKqUBehF5mT5R
      - ACCESS_TOKEN=3432988792-oQ0apU5W29RX0iMPN2JlstoUCDcKWDAMoPyAxMZ
      - ACCESS_TOKEN_SECRET=eMbDEVZV9WqFt2b5JefUh3RQ9mEwATwcthezOWpDOpyba
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  follow_3:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=3
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_3.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=PqiU5uKt76YYoZx2KsYaOiKFy
      - CONSUMER_SECRET=H54Jwtt5zQwC42hK7yAIsNUpOYlopCt0iE9GQqHmO8BQHX1E7o
      - ACCESS_TOKEN=3515187809-ESUiGVGFZQ1lOIQJXZ6yXMHFYbU8Ys6slYtf0jy
      - ACCESS_TOKEN_SECRET=jRtiO20yymDy34kb3TuG4NUjG0GVXBIvik70gDsqmyGUR
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  follow_4:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=4
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_4.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=gtNP9FnACEcdNq4uIZ4Z16y2I
      - CONSUMER_SECRET=78cM2kUrOTVDUi666B7lwJsU8tyjdIWFgYFa1FMN2y7Iqvdiau
      - ACCESS_TOKEN=3514807336-BZ2SV96orDJdnOCtrUcp9cx72JbLsYspsLS4gFm
      - ACCESS_TOKEN_SECRET=StesOR4tmisHkADSw16wBF5YPjnVYEnSwBvspMVlX74Iv
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  follow_5:
    image: istresearch/traptor:v1.3.0
    volumes:
      - logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=follow
      - TRAPTOR_ID=5
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY=true
      - SENTRY_URL=https://870e681805524cddbeadb1957498d4c7:ebcb1d9a15ab4f4f837e0c3694225db5@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor_follow_5.log
      - KAFKA_ENABLED=true
      - KAFKA_HOSTS=crew06.istresearch.com:9092,crew07.istresearch.com:9092,crew08.istresearch.com:9092
      - KAFKA_TOPIC=traptor.cooper_prod
      - REDIS_HOST=memex-services.istresearch.com
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PUBSUB_CHANNEL=traptor-notify-prod
      - CONSUMER_KEY=twkYs7u7HcwU8dHVUn3rUvhQO
      - CONSUMER_SECRET=uX2t5QZSS0OvVoSWNmG7y8fzENo0PACuxGHncXH6uW33ecqHc4
      - ACCESS_TOKEN=3514807336-72OyaEs78GUBo3bHKL0EimfKw3dyhRuFYNB0Ooq
      - ACCESS_TOKEN_SECRET=WMgIKl9a8WvfxfXDuAEJmKgBuBsqeMDhkRJY6LKFKjRBf
      - STATSD_HOST_IP=172.17.0.1
    restart: "on-failure:3"
    depends_on:
      - logstash

  logstash:
    container_name: traptor_logstash
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - /opt/docker_configs/logstash-traptor-prod.conf:/etc/logstash/conf.d/logstash.conf
      - /opt/docker_configs/logs-template.json:/etc/logstash/templates/logs-template.json
      - logs:/var/log/traptor

volumes:
  logs:

