---

logstash_install_dir: /opt/logstash
logstash_version: 2.2.0
logstash_conf_dir: /etc/logstash.d
logstash_template_dir: "{{ logstash_conf_dir }}/templates"
logstash_sincedb_dir: "{{ logstash_install_dir }}/.sincedb"
logstash_auto_start: False
stderr_logfile_maxbytes: 50MB

repository_infrastructure:  "https://download.elastic.co/logstash/logstash"