---
- name: Install Miniconda packages
  shell: "{{ miniconda_install_dir|default('/opt/miniconda') }}/bin/conda install {{ item }} --yes"
  with_items:
    - pip
  tags: traptor

- name: Miniconda pip install traptor
  shell: "{{ miniconda_install_dir|default('/opt/miniconda') }}/bin/pip install traptor"
  tags: traptor

- name: make traptor directory
  file:
    path={{ traptor_install_dir }}
    state=directory
  tags: traptor

- name: create traptor symlink
  file:
    path={{ traptor_install_dir }}/default
    src={{ traptor_miniconda_path }}
    state=link
  tags: traptor

- name: Miniconda pip install packages
  shell: "{{ miniconda_install_dir|default('/opt/miniconda') }}/bin/pip install {{ item }}"
  with_items:
    - requests
    - requests-oauthlib
    - redis
    - kafka-python
    - python-dateutil
    - click
    - scutils
    - pymysql
    - nose
    - flatdict
  tags: traptor

- name: create traptor log directory
  file:
    path={{ traptor_log_dir }}/
    state=directory
    mode=0755
  tags: traptor

- name: copy supervisord config
  template:
    src={{ traptor_name }}-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/{{ traptor_name }}-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: traptor

- name: copy traptor settings
  template:
    src=localsettings.py.j2
    dest={{ traptor_install_dir }}/default/localsettings.py
    mode=0644
  notify:
    - restart traptor
  tags: traptor
